[versions]

[libraries]

# Android
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version ="2.0.4" }

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.7.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core", version = "1.12.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }

# Google
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
google-material = { module = "com.google.android.material:material", version = "1.10.0" }
google-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version = "17.0.1" }

# Common
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }

[plugins]
android-application = { id = "com.android.application", version = "8.1.1" }
android-library = { id = "com.android.library", version = "8.1.1" }
kotlin = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }