[versions]

lifecycle-version = "2.8.7"
exoplayer-version = "1.4.1"
androidx-room = "2.6.1"
google-material = "1.12.0"
google-gson = "2.10.1"
google-dagger-hilt = "2.53.1"
kotlin-coroutines = "1.8.1"
util-aboutlibraries = "11.2.3"
tests-junit = "4.13.2"
tests-junitVersion = "1.2.1"
tests-espressoCore = "3.6.1"

android-plugin  = "8.6.0"
kotlin-plugin = "1.9.22"

[libraries]

# Android
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version ="2.1.3" }

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.8.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-core = { module = "androidx.core:core", version = "1.13.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.8.5" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-version" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-version" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer-version" }
androidx-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayer-version" }
androidx-exoplayer-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer-version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

# Google
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger-hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger-hilt" }

# Utils
util-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
util-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
util-aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "util-aboutlibraries" }
util-aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "util-aboutlibraries" }

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

# Tests
tests-junit = { module = "junit:junit", version.ref = "tests-junit" }
tests-ext-junit = { module = "androidx.test.ext:junit", version.ref = "tests-junitVersion" }
tests-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "tests-espressoCore" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-plugin" }
